version: 2

registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: '${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}'

updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: UTC
    commit-message:
      prefix: build
      include: scope
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 2
    reviewers:
      - 'contentful/team-tolkien'
    registries:
      - npm-registry-registry-npmjs-org
    allow:
      - dependency-name: '@contentful/live-preview'
